# Generated by Django 4.2.4 on 2023-09-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_coupon'),
        ('accounts', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
