# Generated by Django 4.2.4 on 2023-09-07 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_alter_wishlist_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('altMobile', models.IntegerField(blank=True, max_length=10, null=True)),
                ('pincode', models.IntegerField(max_length=6)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('houseNo', models.CharField(max_length=50)),
                ('roadName', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=4)),
                ('addressModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='accounts.addressmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
