# Generated by Django 4.2.4 on 2023-09-09 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_profile_gender_profile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AddressModel',
        ),
    ]
