# Generated by Django 4.2.4 on 2023-09-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_address_addressmodel_delete_addressmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addressModel',
            new_name='user',
        ),
    ]
