# Generated by Django 4.1.11 on 2023-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_addressmodel_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='roadName',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='address',
            name='houseNo',
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
