# Generated by Django 4.1.11 on 2023-09-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutcart',
            name='coupon',
        ),
    ]
