# Generated by Django 4.1.11 on 2023-10-07 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_roadname_address_area_remove_address_houseno_and_more'),
        ('products', '0008_delete_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_checkoutcart_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCheckout',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.coupon')),
                ('product', models.ManyToManyField(blank=True, to='products.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cartCheckout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
