# Generated by Django 4.2.4 on 2023-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default='NAN', max_length=20),
        ),
    ]
